name: Test leanrnware from pip

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    timeout-minutes: 120

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-20.04, ubuntu-22.04, macos-11, macos-latest]
        python-version: [3.8, 3.9, 3.10]

    steps:
    - name: Test learnware from pip
      uses: actions/checkout@v3

    # Since version 3.7 of python for MacOS is installed in CI, version 3.7.17, this version causes "_bz not found error".
    # So we make the version number of python 3.7 for MacOS more specific.
    # refs: https://github.com/actions/setup-python/issues/682

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

     - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    
    - name: Create conda env for macos
      run: |
        conda create -n learnware python=${{ matrix.python-version }}

    