name: Test leanrnware from pip

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    timeout-minutes: 120

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: [3.8, 3.9]

    steps:
    - name: Test learnware from pip
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    
    - name: Create conda env for macos
      run: |
        conda create -n learnware python=${{ matrix.python-version }}

    - name: Update pip to the latest version
      run: |
        conda run -n learnware python -m pip install --upgrade pip
        conda run -n learnware python -m pip install pytest

    - name: Install faiss for MacOS
      if: ${{ matrix.os == 'macos-11' || matrix.os == 'macos-latest' }}
      run: |
        conda run -n learnware conda install -c pytorch faiss

    - name: Install learnware
      run: |
        conda run -n learnware python -m pip install learnware

    - name: Test workflow
      run: |
        conda run -n learnware python -m pytest tests/test_market/test_easy.py
